name: 'Netlify deploy'

on: 
    push:
        branches:
            - 'develop'


jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-18.04
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.PROYECTO_ESTOCASTICOS }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'dist'
